/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FoulType = IDL.Variant({
  'c1' : IDL.Null,
  'c2' : IDL.Null,
  'c3' : IDL.Null,
  'hansokumake' : IDL.Null,
  'hansoku' : IDL.Null,
});
export const Warning = IDL.Record({
  'foul' : FoulType,
  'crowdReaction' : IDL.Nat,
  'issuedBy' : IDL.Nat,
});
export const RecordState = IDL.Record({
  'name' : IDL.Text,
  'yuko' : IDL.Nat,
  'senshu' : IDL.Bool,
  'warnings' : IDL.Vec(Warning),
  'wazaari' : IDL.Nat,
  'isWinner' : IDL.Bool,
  'ippon' : IDL.Nat,
});
export const Time = IDL.Int;
export const RecordMatch = IDL.Record({
  'ao' : RecordState,
  'aka' : RecordState,
  'matchNumber' : IDL.Nat,
  'winner' : IDL.Text,
  'totalTime' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'tatamiNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllMatches' : IDL.Func([], [IDL.Vec(RecordMatch)], ['query']),
  'getDefaultSettings' : IDL.Func(
      [],
      [
        IDL.Record({
          'minutes' : IDL.Nat,
          'seconds' : IDL.Nat,
          'tatamiNumber' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getMatch' : IDL.Func([IDL.Nat], [RecordMatch], ['query']),
  'newMatch' : IDL.Func(
      [
        IDL.Record({
          'akaName' : IDL.Text,
          'category' : IDL.Text,
          'aoName' : IDL.Text,
          'tatamiNumber' : IDL.Text,
        }),
      ],
      [RecordMatch],
      [],
    ),
  'saveMatch' : IDL.Func([RecordMatch], [], []),
  'updateSettings' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FoulType = IDL.Variant({
    'c1' : IDL.Null,
    'c2' : IDL.Null,
    'c3' : IDL.Null,
    'hansokumake' : IDL.Null,
    'hansoku' : IDL.Null,
  });
  const Warning = IDL.Record({
    'foul' : FoulType,
    'crowdReaction' : IDL.Nat,
    'issuedBy' : IDL.Nat,
  });
  const RecordState = IDL.Record({
    'name' : IDL.Text,
    'yuko' : IDL.Nat,
    'senshu' : IDL.Bool,
    'warnings' : IDL.Vec(Warning),
    'wazaari' : IDL.Nat,
    'isWinner' : IDL.Bool,
    'ippon' : IDL.Nat,
  });
  const Time = IDL.Int;
  const RecordMatch = IDL.Record({
    'ao' : RecordState,
    'aka' : RecordState,
    'matchNumber' : IDL.Nat,
    'winner' : IDL.Text,
    'totalTime' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'tatamiNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllMatches' : IDL.Func([], [IDL.Vec(RecordMatch)], ['query']),
    'getDefaultSettings' : IDL.Func(
        [],
        [
          IDL.Record({
            'minutes' : IDL.Nat,
            'seconds' : IDL.Nat,
            'tatamiNumber' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getMatch' : IDL.Func([IDL.Nat], [RecordMatch], ['query']),
    'newMatch' : IDL.Func(
        [
          IDL.Record({
            'akaName' : IDL.Text,
            'category' : IDL.Text,
            'aoName' : IDL.Text,
            'tatamiNumber' : IDL.Text,
          }),
        ],
        [RecordMatch],
        [],
      ),
    'saveMatch' : IDL.Func([RecordMatch], [], []),
    'updateSettings' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };