/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FoulType = { 'c1' : null } |
  { 'c2' : null } |
  { 'c3' : null } |
  { 'hansokumake' : null } |
  { 'hansoku' : null };
export interface RecordMatch {
  'ao' : RecordState,
  'aka' : RecordState,
  'matchNumber' : bigint,
  'winner' : string,
  'totalTime' : string,
  'timestamp' : Time,
  'category' : string,
  'tatamiNumber' : string,
}
export interface RecordState {
  'name' : string,
  'yuko' : bigint,
  'senshu' : boolean,
  'warnings' : Array<Warning>,
  'wazaari' : bigint,
  'isWinner' : boolean,
  'ippon' : bigint,
}
export type Time = bigint;
export interface Warning {
  'foul' : FoulType,
  'crowdReaction' : bigint,
  'issuedBy' : bigint,
}
export interface _SERVICE {
  'getAllMatches' : ActorMethod<[], Array<RecordMatch>>,
  'getDefaultSettings' : ActorMethod<
    [],
    { 'minutes' : bigint, 'seconds' : bigint, 'tatamiNumber' : string }
  >,
  'getMatch' : ActorMethod<[bigint], RecordMatch>,
  'newMatch' : ActorMethod<
    [
      {
        'akaName' : string,
        'category' : string,
        'aoName' : string,
        'tatamiNumber' : string,
      },
    ],
    RecordMatch
  >,
  'saveMatch' : ActorMethod<[RecordMatch], undefined>,
  'updateSettings' : ActorMethod<
    [[] | [string], [] | [bigint], [] | [bigint]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];