/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RecordMatch {
    ao: RecordState;
    aka: RecordState;
    matchNumber: bigint;
    winner: string;
    totalTime: string;
    timestamp: Time;
    category: string;
    tatamiNumber: string;
}
export type Time = bigint;
export interface Warning {
    foul: FoulType;
    crowdReaction: bigint;
    issuedBy: bigint;
}
export interface RecordState {
    name: string;
    yuko: bigint;
    senshu: boolean;
    warnings: Array<Warning>;
    wazaari: bigint;
    isWinner: boolean;
    ippon: bigint;
}
export enum FoulType {
    c1 = "c1",
    c2 = "c2",
    c3 = "c3",
    hansokumake = "hansokumake",
    hansoku = "hansoku"
}
export interface backendInterface {
    getAllMatches(): Promise<Array<RecordMatch>>;
    getDefaultSettings(): Promise<{
        minutes: bigint;
        seconds: bigint;
        tatamiNumber: string;
    }>;
    getMatch(matchId: bigint): Promise<RecordMatch>;
    newMatch(params: {
        akaName: string;
        category: string;
        aoName: string;
        tatamiNumber: string;
    }): Promise<RecordMatch>;
    saveMatch(newMatch: RecordMatch): Promise<void>;
    updateSettings(newTatami: string | null, newMinutes: bigint | null, newSeconds: bigint | null): Promise<void>;
}
import type { FoulType as _FoulType, RecordMatch as _RecordMatch, RecordState as _RecordState, Time as _Time, Warning as _Warning } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllMatches(): Promise<Array<RecordMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDefaultSettings(): Promise<{
        minutes: bigint;
        seconds: bigint;
        tatamiNumber: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultSettings();
            return result;
        }
    }
    async getMatch(arg0: bigint): Promise<RecordMatch> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_RecordMatch_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_RecordMatch_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async newMatch(arg0: {
        akaName: string;
        category: string;
        aoName: string;
        tatamiNumber: string;
    }): Promise<RecordMatch> {
        if (this.processError) {
            try {
                const result = await this.actor.newMatch(arg0);
                return from_candid_RecordMatch_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.newMatch(arg0);
            return from_candid_RecordMatch_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveMatch(arg0: RecordMatch): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMatch(to_candid_RecordMatch_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMatch(to_candid_RecordMatch_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSettings(arg0: string | null, arg1: bigint | null, arg2: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(to_candid_opt_n20(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(to_candid_opt_n20(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_FoulType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoulType): FoulType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_RecordMatch_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecordMatch): RecordMatch {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_RecordState_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecordState): RecordState {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Warning_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Warning): Warning {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ao: _RecordState;
    aka: _RecordState;
    matchNumber: bigint;
    winner: string;
    totalTime: string;
    timestamp: _Time;
    category: string;
    tatamiNumber: string;
}): {
    ao: RecordState;
    aka: RecordState;
    matchNumber: bigint;
    winner: string;
    totalTime: string;
    timestamp: Time;
    category: string;
    tatamiNumber: string;
} {
    return {
        ao: from_candid_RecordState_n4(_uploadFile, _downloadFile, value.ao),
        aka: from_candid_RecordState_n4(_uploadFile, _downloadFile, value.aka),
        matchNumber: value.matchNumber,
        winner: value.winner,
        totalTime: value.totalTime,
        timestamp: value.timestamp,
        category: value.category,
        tatamiNumber: value.tatamiNumber
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    yuko: bigint;
    senshu: boolean;
    warnings: Array<_Warning>;
    wazaari: bigint;
    isWinner: boolean;
    ippon: bigint;
}): {
    name: string;
    yuko: bigint;
    senshu: boolean;
    warnings: Array<Warning>;
    wazaari: bigint;
    isWinner: boolean;
    ippon: bigint;
} {
    return {
        name: value.name,
        yuko: value.yuko,
        senshu: value.senshu,
        warnings: from_candid_vec_n6(_uploadFile, _downloadFile, value.warnings),
        wazaari: value.wazaari,
        isWinner: value.isWinner,
        ippon: value.ippon
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    foul: _FoulType;
    crowdReaction: bigint;
    issuedBy: bigint;
}): {
    foul: FoulType;
    crowdReaction: bigint;
    issuedBy: bigint;
} {
    return {
        foul: from_candid_FoulType_n9(_uploadFile, _downloadFile, value.foul),
        crowdReaction: value.crowdReaction,
        issuedBy: value.issuedBy
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    c1: null;
} | {
    c2: null;
} | {
    c3: null;
} | {
    hansokumake: null;
} | {
    hansoku: null;
}): FoulType {
    return "c1" in value ? FoulType.c1 : "c2" in value ? FoulType.c2 : "c3" in value ? FoulType.c3 : "hansokumake" in value ? FoulType.hansokumake : "hansoku" in value ? FoulType.hansoku : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecordMatch>): Array<RecordMatch> {
    return value.map((x)=>from_candid_RecordMatch_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Warning>): Array<Warning> {
    return value.map((x)=>from_candid_Warning_n7(_uploadFile, _downloadFile, x));
}
function to_candid_FoulType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoulType): _FoulType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_RecordMatch_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordMatch): _RecordMatch {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_RecordState_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordState): _RecordState {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Warning_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Warning): _Warning {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ao: RecordState;
    aka: RecordState;
    matchNumber: bigint;
    winner: string;
    totalTime: string;
    timestamp: Time;
    category: string;
    tatamiNumber: string;
}): {
    ao: _RecordState;
    aka: _RecordState;
    matchNumber: bigint;
    winner: string;
    totalTime: string;
    timestamp: _Time;
    category: string;
    tatamiNumber: string;
} {
    return {
        ao: to_candid_RecordState_n13(_uploadFile, _downloadFile, value.ao),
        aka: to_candid_RecordState_n13(_uploadFile, _downloadFile, value.aka),
        matchNumber: value.matchNumber,
        winner: value.winner,
        totalTime: value.totalTime,
        timestamp: value.timestamp,
        category: value.category,
        tatamiNumber: value.tatamiNumber
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    yuko: bigint;
    senshu: boolean;
    warnings: Array<Warning>;
    wazaari: bigint;
    isWinner: boolean;
    ippon: bigint;
}): {
    name: string;
    yuko: bigint;
    senshu: boolean;
    warnings: Array<_Warning>;
    wazaari: bigint;
    isWinner: boolean;
    ippon: bigint;
} {
    return {
        name: value.name,
        yuko: value.yuko,
        senshu: value.senshu,
        warnings: to_candid_vec_n15(_uploadFile, _downloadFile, value.warnings),
        wazaari: value.wazaari,
        isWinner: value.isWinner,
        ippon: value.ippon
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    foul: FoulType;
    crowdReaction: bigint;
    issuedBy: bigint;
}): {
    foul: _FoulType;
    crowdReaction: bigint;
    issuedBy: bigint;
} {
    return {
        foul: to_candid_FoulType_n18(_uploadFile, _downloadFile, value.foul),
        crowdReaction: value.crowdReaction,
        issuedBy: value.issuedBy
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoulType): {
    c1: null;
} | {
    c2: null;
} | {
    c3: null;
} | {
    hansokumake: null;
} | {
    hansoku: null;
} {
    return value == FoulType.c1 ? {
        c1: null
    } : value == FoulType.c2 ? {
        c2: null
    } : value == FoulType.c3 ? {
        c3: null
    } : value == FoulType.hansokumake ? {
        hansokumake: null
    } : value == FoulType.hansoku ? {
        hansoku: null
    } : value;
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Warning>): Array<_Warning> {
    return value.map((x)=>to_candid_Warning_n16(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
